{pkgs, config, ...}:
{
  home.file = { 
    # You can also set the file content immediately.
    ".config/kitty/kitty.conf".text = ''
      # Generated by Home Manager.
      # See https://sw.kovidgoyal.net/kitty/conf.html
      font_family Fira Code Nerd Font
      font_size 12

      # Shell integration is sourced and configured manually
      shell_integration no-rc

      linux_display_server x11

      background #24273a

      dynamic_background_opacity yes
      background_opacity 0.95

      enable_audio_bell no
    ''; 
  };  
}
